### ISSUE TITLE
Remove AppCompat styles

### ISSUE THREAD

**Issue by daniel-stoneuk** [daniel-stoneuk/material-about-library#106]
Mentioned in #105 

Replace styles with

mal_material_about_list_card
@style/TextAppearance.MaterialComponents.Headline6

mal_material_about_title_item
@style/TextAppearance.MaterialComponents.Headline5
@style/TextAppearance.MaterialComponents.Body2

Cheers @marcardar

**Comment by marcardar** [comment]
Thanks Daniel. I've been playing around with:

title: TextAppearance.MaterialComponents.Headline6
subtitle: TextAppearance.MaterialComponents.Subtitle2

but the title looks very big to me, even though Headline6 is supposed to be the smallest. What do you think?

Also, should the text in title_item and action_item look the same?  If so, should that part be extracted into its own layout part and then "included" in the two different existing layouts.

**Comment by marcardar** [comment]
I just realised that, anyway, we should be using ?attr/ rather than the style resources directly. And it looks better because we can use the proper text appearance attrs for lists (and no need to tweak the text size):

**title**: ?android:attr/textAppearanceListItem
**subtitle**: ?android:attr/textAppearanceListItemSecondary (and personally I prefer to add android:textColor="?android:attr/textColorSecondary")

**card title**: ?attr/textAppearanceHeadline6

**Comment by daniel-stoneuk** [comment]
Yep, currently quite busy - will try and get round to this in the following week. Thanks :)

**Comment by daniel-stoneuk** [comment]
Reopening as I'm not sure why I closed this. Will make these changes or accept a PR for them :)

**Comment by daniel-stoneuk** [comment]
Line 52 in library/src/main/res/layout/mal_material_about_title_item.xml needs fixing
