### ISSUE TITLE
AboutActivity with NavigationDrawer

### ISSUE THREAD

**Issue by Nexen23** [daniel-stoneuk/material-about-library#6]
Is there a way to add left NavigationView for AboutActivity & use Hamburger instead of Up button inside Toolbar?

**Comment by daniel-stoneuk** [comment]
Hi Alex,

I'll be working on fragment support later this weekend, which would let you
use the library with a NavagationView.

Cheers,
Dan
On Mon, 2 Jan 2017, 6:55 pm Alex, <notifications@github.com> wrote:

Is there a way to add left NavigationView for AboutActivity & use Hamburger
instead of Up button inside Toolbar?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/daniel-stoneuk/material-about-library/issues/6>, or mute
the thread

**Comment by daniel-stoneuk** [comment]
Hopefully you're using fragments with your NavigationDrawer - if so, it should be relatively simple to create a fragment with version 1.3.0. Check out the demo app to see how to implement it.

If you end up using it I'd love to see the app! Thanks!
