### ISSUE TITLE
Are you interested in merging my changes?

### ISSUE THREAD

**Issue by ueman** [daniel-stoneuk/material-about-library#8]
I've added the following things:
- You can start an About Page with only an Intent (with an IntentBuilder)
- Some enhancements to your code
- Some premade Items wich you can simply add with the ConvenienceBuilder class

I would tidy up my code a little bit and would then open a pull request.
You can take a look at my changes here: https://github.com/ueman/material-about-library/

**Comment by daniel-stoneuk** [comment]
Your code looks interesting! If I'm honest, I wouldn't want to merge all of it but I've just spent some time looking through your code and it looks great.

I'm not sure about starting the about page with only an intent, I decided to go for extending an abstract class as it allows for more functionality and because it's not possible (as far as I'm aware) to pass in the MaterialAboutList - I've tried parceling but obviously that didn't work out.

I however, love the idea of the ConvenienceBuilder class. I would like to merge that but don't think bundling icons with the library is a good idea. Maybe you could make the builders less specific (eg remove the facebook one but leave the website one).

I'm sorry if I'm being a bit picky and I hope you're not offended or anything! I really do appreciate the work you've done on the library.

You could open a pull request and then I can refactor the code to only include the things I would like to implement?

**Comment by ueman** [comment]
The IntentBuilder for the AboutPage was intended as an addon for even simpler creation of an AboutPage.
Yeah, I'm not offended or anything.
I'm doing a Pull Request then and you can do whatever you want with it.

**Comment by daniel-stoneuk** [comment]
I'm going to be slightly busy over the next couple days, so will merge this weekend. Thanks again!

**Comment by ueman** [comment]
You could also look into this [commit](https://github.com/ueman/material-about-library/commit/1b3b8133b416c8dbec2ad137304094731e106568) on how to simplify you code a little bit and on how to remove those instanceof if-else things. Unfortunatly that code isn't in the pull request because I messed up. Sorry about that.
